name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        build_type: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set nix environment
        uses: nicknovitski/nix-develop@v1
      - name: Build in ${{ matrix.build_type }} mode
        run: cargo build --profile ${{ matrix.build_type }}
      - name: Run tests
        run: cargo test --profile ${{ matrix.build_type }}
