name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    name: "Build and test"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        build_type: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v21
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - name: Set Git credentials
        run: |
          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://git@github.com/'
          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com:'
          echo 'echo "$CI_BOT_PAT"' > ~/.git-askpass
          chmod 500 ~/.git-askpass
          git config --global core.askPass "$HOME"/.git-askpass
      - name: Set nix environment
        uses: nicknovitski/nix-develop@v1
        env:
          CI_BOT_PAT: "${{ secrets.CI_BUILD_TOKEN }}"
      - name: Build in ${{ matrix.build_type }} mode
        run: cargo build --profile ${{ matrix.build_type }}
      - name: Run tests
        run: cargo test --profile ${{ matrix.build_type }}
      - name: Clear Git credentials
        if: "${{ always() }}"
        run: rm -rf "~/.git-askpass"
